In [1]:
import numpy as np

In [2]:
numeros =[1,2,3,4]

In [4]:
array = np.array(numeros)

In [5]:
array

array([1, 2, 3, 4])

In [7]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(5
       )

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [15]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [16]:
np.random.randint(0,100,10)

array([48, 40, 12, 71, 77, 61, 18, 51, 94, 93])

In [18]:
array = np.random.randint(0,100,10)

In [19]:
array

array([12, 93, 92, 54, 59, 52, 65, 74, 75, 20])

In [20]:
array.max()

93

In [22]:
array.min()

12

In [24]:
array.argmax()

1

In [25]:
array

array([12, 93, 92, 54, 59, 52, 65, 74, 75, 20])

In [26]:
array.reshape(5,2)

array([[12, 93],
       [92, 54],
       [59, 52],
       [65, 74],
       [75, 20]])

In [27]:
array = array.reshape(5,2)

In [30]:
array[2,0]

59

In [36]:
filtro = array < 20
array2 = array[filtro]

In [33]:
array2

array([12, 93, 92, 54, 59, 52, 65, 74, 75, 20])

In [35]:
array2

array([93, 92, 54, 59, 52, 65, 74, 75])

In [37]:
array2

array([12])